Set up testing framework - RSpec
CraftAcademy/rails_messaging_aug18-team5 pull request #1
Opened 2018-09-18 11:34 UTC by RhonGabriel

Added the following gem to group :development, :test
- gem 'factory_bot_rails'
- gem 'pry-byebug'
- gem 'pry-rails'
- gem 'rspec-rails'
- gem 'shoulda-matchers'
Executed Rspec generator

PV
https://www.pivotaltracker.com/story/show/160582051

2018-09-18 11:46 UTC, tochman requested changes
These commits are also part of the next PR. Why is that?

2018-09-19 07:56 UTC, tochman requested changes

2018-09-19 07:56 UTC, tochman commented on .rspec
> +--require spec_helper
require `rails_helper` here

2018-09-19 07:56 UTC, tochman commented on Gemfile
> +ruby '2.5.1'
Never change this.

2018-09-19 07:56 UTC, tochman commented on Gemfile
> +  gem 'cucumber-rails', require: false
???

2018-09-19 07:56 UTC, tochman commented on Gemfile
> +  gem 'database_cleaner'
???

2018-09-19 07:56 UTC, tochman commented on features/support/env.rb
> +
Out of scope. Relates to cucumber

2018-09-19 07:56 UTC, tochman commented on spec/rails_helper.rb
> +end
Please remove comments in file

2018-09-19 07:56 UTC, tochman commented on spec/spec_helper.rb
> +end
Please remove comments

2018-09-19 09:37 UTC, RhonGabriel commented
Fixed issue with ruby version and deleted comments from spec folder (rails_helper.rb and spec_helper.rb)

2018-09-19 09:43 UTC, tochman approved these changes
Looks good to me. Good job.

2018-09-19 09:43 UTC, merged