User can login to account
CraftAcademy/rails_messaging_aug18-team5 pull request #5
Opened 2018-09-19 13:56 UTC by RhonGabriel

# PT
link https://www.pivotaltracker.com/story/show/160581978

# User story
```
As a User
When I visit the application,
I would like to be able to login
```
# Task
```
Create feature file name “login_to_account.feature”
Create a file in step definitions called "login_to_account_steps.rb"
Create FactoryBot
```
# No gems

2018-09-19 15:36 UTC, tochman submitted a review, later dismissed

2018-09-19 15:36 UTC, tochman commented on features/step_definitions/login_to_account_steps.rb
> +When("I fill in {string} with {string}") do |string, string2|
Please name the variables

2018-09-19 15:36 UTC, tochman commented on features/login_to_account.feature
> +    I visit the application,
Check the format of this user story. I sense a missing ‘when’

2018-09-19 15:36 UTC, tochman commented on features/login_to_account.feature
> +    I visit the application,
But also, why would the user want to log in. What’s the purpose (business objective)?

2018-09-19 15:41 UTC, SophieSjoberg requested changes
Well done, see and adress my comments please 👍

2018-09-19 15:41 UTC, SophieSjoberg commented on features/login_to_account.feature
> +    I would like to be able to log in to my existing account
You have to revisit this user story - how do you write them? Thinking about line 4 here.

2018-09-19 15:41 UTC, SophieSjoberg commented on features/login_to_account.feature
> +    Given User has an existing account
Would probably rephrase this to make it more specific. Given the following user exist

2018-09-19 15:41 UTC, SophieSjoberg commented on features/step_definitions/login_to_account_steps.rb
> +end
We do not name the arguments sting or string2. Change those and be specific

2018-09-19 17:12 UTC, RhonGabriel commented
@tochman @SophieSjoberg thanks for the suggestions. I modified the user story to state its purpose and gave name to generic variables

2018-09-20 07:42 UTC, SophieSjoberg approved these changes

2018-09-20 07:43 UTC, merged